FROM mohanna/teastore-base:development
MAINTAINER Chair of Software Engineering <se2-it@informatik.uni-wuerzburg.de>

COPY target/*.war /usr/local/tomcat/webapps/
COPY src/main/resources/cgt_config.yaml /usr/local/tomcat/webapps/
